name: Code Quality

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    # 前端代码质量检查
    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci
      
    - name: Run frontend linting
      working-directory: ./frontend
      run: npm run lint
      
    - name: Check frontend formatting
      working-directory: ./frontend
      run: npm run check-format
      
    # 后端代码质量检查
    - name: Install backend dependencies
      working-directory: ./backend
      run: npm ci
      
    - name: Run backend linting
      working-directory: ./backend
      run: npm run lint
      
    - name: Check backend formatting
      working-directory: ./backend
      run: npm run check-format
      
    # 代码覆盖率检查
    - name: Run frontend tests with coverage
      working-directory: ./frontend
      run: npm run test:coverage
      
    - name: Run backend tests with coverage
      working-directory: ./backend
      run: npm run test:coverage
      
    # 上传覆盖率报告
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./frontend/coverage/lcov.info,./backend/coverage/lcov.info
        flags: frontend,backend
        name: codecov-umbrella
        fail_ci_if_error: false 